import "./globals.css";
import { Inter, M_PLUS_1 } from "next/font/google";

const m_plus_1 = M_PLUS_1({ subsets: ["latin"] });

export const metadata = {
  title: "Ngaji Tanya Jawab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={m_plus_1.className}>{children}</body>
    </html>
  );
}
